export const enum Status {
	SUCCESS,
	ERR_NO_CLIENT_INSTANCE,
	ERR_CLIENT_INSTANCE_EXISTS,
	ERR_DEVICE_ALREADY_EXISTS,
	ERR_DEVICE_NOT_FOUND,
	ERR_DEVICE_ALREADY_OPENED,
	ERR_DEVICE_NOT_OPENED,
	ERR_DEVICE_INTERFACE_NOT_FOUND,
	ERR_DEVICE_INTERFACE_ALREADY_CLAIMED,
	ERR_DEVICE_INTERFACE_NOT_CLAIMED,
}
